service: entity-pre-store

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: us-west-2

package:
  artifact: target/entity-pre-store.jar

functions:
  currentTime:
    handler: com.serverless.Handler
